<?php
namespace Chatbox\Mail;

use SendGrid;
use SendGrid\Email;
/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2015/03/28
 * Time: 13:15
 */

class SendGridMailer extends MailerBase{

    static protected $defaultConfig;

    static public function setDefaultConfig($sendgrid_username, $sendgrid_password, $options=[]){
        if(func_num_args() == 2 ){
            $options = ["turn_off_ssl_verification" => true];
        }
        static::$defaultConfig = new SendGrid($sendgrid_username,$sendgrid_password,$options);
    }

    private $sendGrid;

    /**
     * @var Email
     */
    private $email;

    /**
     * @param $to
     * @param $subject
     * @param $body
     * @param null $headers
     * @param null $param
     */
    function __construct($to, $subject, $body, $headers = null, $param = null)
    {
        if(!class_exists("SendGrid")){
            throw new \DomainException("dont exist SendGrid Class");
        }
        parent::__construct($to, $subject, $body, $headers, $param); // TODO: Change the autogenerated stub
        $this->email = new Email;
    }


    public function setSendGrid(SendGrid $sendGrid=null){
        $this->sendGrid = $sendGrid;
    }

    public function getSendGrid(){
        if(is_null($this->sendGrid) && static::$defaultConfig){
            return static::$defaultConfig;
        }else if($this->sendGrid){
            return $this->sendGrid;
        }else{
            throw new \Exception("No Sendgrid Object");
        }
    }

    public function getEmail(){
        return $this->email;
    }

    public function send()
    {
        $email = new Email();
        $this->email
            ->setTos($this->to)
            ->setSubject($this->subject)
            ->setText($this->body);
    }


}